### ISSUE TITLE
Global Install instructions?

### ISSUE THREAD

**Issue by deadcoder0904** [sublimelsp/LSP-biome#12]
I have some scripts that I run from any folder.

Usually, I install prettier but thought I should give biome a try.

But can't get installation to work.

I installed biome globally through `npm i -g biome` & then put this in my preferences:

```json
// Settings in here override those in "LSP-biome/LSP-biome.sublime-settings"

{
    "biome.requireConfiguration": false,
    "lsp_code_actions_on_save": {
        "quickfix.biome": true
    },
    "organizeImports": {
        "enabled": true
    },
    "lsp_code_actions_on_save":{
        "source.organizeImports.biome": true
    }
}
```

but I can't get it to work on a global level. Also, I can't see `format document` when I open **package control** & type `lsp` or `biome`

For prettier, I do the same & it worked. Prettier Sublime also has a massive default configuration file which I can edit. I would like that in Biome Sublime too.

I literally uninstalled prettier after installing it to try biome. Why doesn't biome work similarly?

I also saw the note which links to https://biomejs.dev/guides/how-biome-works/ but sadly, I don't get how to make it work. Any ideas?

> Note: I want global installation that works on any file even if it isn't in project. I have a few configurations like use tabs, only 2 indents, no semicolon, & singlequote. That's it.

**Comment by rchl** [comment]
Settings in `LSP-biome.sublime-settings` need to match the structure on the left so be within a `settings` object.

Also those are not part of biome settings:

```
    "lsp_code_actions_on_save": {
        "quickfix.biome": true
    },
    "organizeImports": {
        "enabled": true
    },
    "lsp_code_actions_on_save":{
        "source.organizeImports.biome": true
    }
```

Those should be in global LSP settings. Something like:

```
    "lsp_code_actions_on_save": {
        "quickfix.biome": true,
        "source.organizeImports.biome": true
    },
```

**Comment by deadcoder0904** [comment]
and what should i paste there?

i tried what you said. i pasted this:

```json
// Settings in here override those in "LSP-biome/LSP-biome.sublime-settings"

{
	"settings": {
			"lsp_code_actions_on_save": {
				"quickfix.biome": true,
				"source.organizeImports.biome": true
			},
			"biome.requireConfiguration": false
	}
}
```

but that didn't do anything.

**Comment by rchl** [comment]
That's not what I said. Re-read my message.

**Comment by deadcoder0904** [comment]
alright, i tried putting them in lsp settings. here's how it looks like now:

### LSP.sublime-settings

```json
// Settings in here override those in "LSP/LSP.sublime-settings"
{
	  "lsp_format_on_save": true,
  	"lsp_code_actions_on_save": {
      "quickfix.biome": true,
      "source.organizeImports.biome": true
    },
}
```

### LSP-biome.sublime-settings

```json
// Settings in here override those in "LSP-biome/LSP-biome.sublime-settings"

{
	"settings": {
		"biome.lspBin": "C:\\Program Files\biomejs\biome.exe"
	}
}
```

And I've added `biome.exe` to my Windows Environment Variables Path as well.

That's supposed to work, right? It isn't.

I get an error saying `LSP Biome Server has crashed 5 times in 180 seconds`

Is there a minimum configuration at all?

**Comment by rchl** [comment]
`LSP-biome` by default installs and manages the biome server so you don't have to install it on your own.
Also you still need `"biome.requireConfiguration": false` if you want it to work without configuration file.

**Comment by deadcoder0904** [comment]
alright, that did the trick, thanks!

i think a minimal guide on `README.md` would be helpful or point them here:

this is what worked for me.

### LSP.sublime-settings

```json
// Settings in here override those in "LSP/LSP.sublime-settings"
{
	  "lsp_format_on_save": true,
  	"lsp_code_actions_on_save": {
      "quickfix.biome": true,
      "source.organizeImports.biome": true
    },
}
```

### LSP-biome.sublime-settings

```json
// Settings in here override those in "LSP-biome/LSP-biome.sublime-settings"

{
	"settings": {
		// Disables formatting, linting, and syntax errors for projects without a biome.json file. Enabled by default.
		"biome.requireConfiguration": false,
	},	
}
```

**Comment by rchl** [comment]
Readme already covers it but you weren't really following it very well.

**Comment by jackTabsCode** [comment]
Hey @rchl, I've configured my LSP settings as such:
```json
    "lsp_code_actions_on_save": {
        "quickfix.biome": true,
        "source.organizeImports.biome": true
    },
 ```

The LSP *does* appear to be formatting my code and I am getting diagnostics, but it refuses to fix any fixable lints and refuses to organize imports or remove unused ones.

I feel like I've tried every single possible code action setting, and nothing is working.
